### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by shtefcs** [xiyuan-fengyu/ppspider#1]
Hi Xiyuan,

I wanted to reach you since you build this Puppeteer spider. 

We are re-building [Automatio.co](https://automatio.co), which is visual scraper.  We are looking for a developer for contract work.

If you are interested, let me know and we can chat further.

Stefan
email:stefan@vanila.io

**Comment by xiyuan-fengyu** [comment]
You may send email to me.  
xiyuan_fengyu@163.com
