### ISSUE TITLE
内存泄露和重复爬行

### ISSUE THREAD

**Issue by semmy2010** [xiyuan-fengyu/ppspider#10]
1. 我在@Launcher配置dbUrl为mongodb，爬行时间较长时，硬盘虚拟内存一直升高，直到硬盘容量耗尽，爬行卡住(在web ui那边看，running的任务不变化)，是否有内存泄露了 ？爬行任务里有用到puppeteer，刚开始爬行，chrome进程正常并发几个，也会销毁，是正常的，爬行久了(一天一夜)，在任务管理器里发现好多chrome的进程，有上百个chrome进程。
```
const page = await this.browser.newPage();
//do something ...
await page.close();
```

2. 通过webUi界面上的shutdown and save 的按钮来停止爬虫应用，但是第二次开启，OnStart还是会再执行，如何通过OnStart和AddToQueue，FromQueue的组合来解决？

**Comment by xiyuan-fengyu** [comment]
1. 框架里面已经封装了puppeteer page的创建和关闭，puppeteer的正确使用方式可参考  
https://github.com/xiyuan-fengyu/ppspider/blob/master/src/test/component/ProxyTest.ts  
https://github.com/xiyuan-fengyu/ppspider_example/blob/master/src/examples/DepthFirstSearchApp.ts  
https://github.com/xiyuan-fengyu/ppspider_example/blob/master/src/examples/PuppeteerEvalAsyncApp.ts  
正常情况下，长时间运行chrome进程数也会很稳定  
另外在ui上检查一下队列是否存在堆积情况，这个是因为任务之间的并行数不协调，导致下游url产出速度远大于FromQueue的处理速度，这样时间久了，队列堆积，内存也会耗尽  
2. 代码如下  
```
class Test {

    @OnStart({url: ""})
    @AddToQueue({name: "test_queue"})
    async addStartUrl() {
        return "the start url";
   }

    @FromQueue({name: "test_queue"})
    async doSomething(job: Job) {
   
    }

}
```
