### ISSUE TITLE
@OnTime定时器不准确

### ISSUE THREAD

**Issue by semmy2010** [xiyuan-fengyu/ppspider#12]
我想要的效果是程序启动时马上执行一次(也是`2019-10-17 13:23`执行一次)，然后是`2019-10-17 15:23`，再执行一次，这个目前可以实现吗？  
我通过以下的代码，却无法实现我想要的效果。
实际效果我通过打开WebUI看了下，lastExeTime为空，nextExeTime是`2019-10-17 14:00:00`。  这是为什么？
```
@OnTime({
	description: '每2个小时执行一次',
	urls: 'http://www.baidu.com',
	cron: '* * */2 * * *',
	running: true
})
async test(page: Page, job: Job) {
    console.log(job.url);
}
```

**Comment by semmy2010** [comment]
还会出现一种诡异的事情，我在`2019-10-18 00:00`之后执行上面代码，变成几乎是每秒会执行一次。（如图）：
![123](https://user-images.githubusercontent.com/4402907/67027420-1a1dc080-f13c-11e9-9c02-5fecab3414a1.png)

**Comment by xiyuan-fengyu** [comment]
这个cron表达式 '* * */2 * * *' 的意思是偶数小时期间内，每秒执行一次

**Comment by xiyuan-fengyu** [comment]
参考  
https://www.npmjs.com/package/cron

**Comment by xiyuan-fengyu** [comment]
如果你想要每两小时执行一次，cron可以是 '0 0 */2 * * *'

**Comment by xiyuan-fengyu** [comment]
如果希望启动时立即执行一次，可以再加上一个 @OnStart
