### ISSUE TITLE
想问一下puppeteer+ts， 如何支持window document等属性

### ISSUE THREAD

**Issue by fangdown** [xiyuan-fengyu/ppspider#14]
想问一下puppeteer+ts， 如何支持window document等属性，在vscode中目前是报错的

**Comment by xiyuan-fengyu** [comment]
我没在vs中开发过，不过你可以试试在tsconfig.json中添加配置    
```
"lib": [
    "dom"
  ]
```
参考 https://github.com/xiyuan-fengyu/ppspider/blob/master/tsconfig.json

**Comment by fangdown** [comment]
谢谢，增加了dom 确实可以解决


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiyuan-fengyu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 下午5:07
收件人:&nbsp;"xiyuan-fengyu/ppspider"<ppspider@noreply.github.com&gt;;
抄送:&nbsp;"409951398"<409951398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiyuan-fengyu/ppspider] 想问一下puppeteer+ts， 如何支持window document等属性 (#14)




我没在vs中开发过，不过你可以试试
 "lib": [     "es6",     "dom"   ]

**Comment by fangdown** [comment]
已解决，3q
