### ISSUE TITLE
jobInfo的maxTry设置错误

### ISSUE THREAD

**Issue by gebing** [xiyuan-fengyu/ppspider#16]
以下的代码都没有考虑maxTry为负数时的情况。如：jobInfo._.maxTry = null，queueInfo.config.maxTry = -1，则最后的结果maxTry是0，显然是错误的。

```
                jobInfo._.maxTry = Math.max(jobInfo._.maxTry || 0, queueInfo.config.maxTry || Defaults.maxTry);
```

**Comment by xiyuan-fengyu** [comment]
maxTry 的设置有点绕，改了一下  
https://github.com/xiyuan-fengyu/ppspider/commit/8c58812f4b21706c6ea3820e835fad58a5a78bcc  
https://github.com/xiyuan-fengyu/ppspider_example/blob/master/src/examples/SetMaxTryApp.ts

**Comment by gebing** [comment]
Thanks.
