### ISSUE TITLE
Cannot find name 'Element'

### ISSUE THREAD

**Issue by xindg** [xiyuan-fengyu/ppspider#2]
windows 10 + vscode 
run tsc
tips:
 File change detected. Starting incremental compilation...

node_modules/ppspider/lib/puppeteer/PuppeteerUtil.d.ts:33:48 - error TS2304: Cannot find name 'Element'.

33 export declare type ElementTransformer = (ele: Element) => Href | void;

try 2.1.8 , 2.1.6 ver
The same problem.

**Comment by xindg** [comment]
fix it
tsconfig.json
add 
lib "dom"

    "target": "es2016",
    "lib": [
      "es6",
      "dom"
    ],

**Comment by xiyuan-fengyu** [comment]
good job
