### ISSUE TITLE
有木有真实案例可以分享下

### ISSUE THREAD

**Issue by zhengxs2018** [xiyuan-fengyu/ppspider#22]
互相交流下，最近想采集一些 (开放，无争议) 数据自用。

我写的，待完善中～

https://github.com/zhengxs2018/hzfc-reiva-spider

**Comment by xiyuan-fengyu** [comment]
很棒的实战项目，欢迎分享

**Comment by zhengxs2018** [comment]
@xiyuan-fengyu 大佬有米有自己的案例要不要建一个开源群，拉人互相交流啊

**Comment by xiyuan-fengyu** [comment]
我这边能分享出来的例子都放在文档中了，后面我再写一些例子加进去、新建了个qq群：725187346，但感觉可能没几个人加

**Comment by zhengxs2018** [comment]
建立个微信或钉钉群么，我qq好久没登录了，自从用了 苹果电脑，现在 qq 都删除了

有群就慢慢就有人来了么，不然都没人交流
