### ISSUE TITLE
custom filter

### ISSUE THREAD

**Issue by gankbat** [xiyuan-fengyu/ppspider#3]

**Comment by gankbat** [comment]
我想自定义一个过滤器，需要查询数据库，目前的代码似乎不支持

**Comment by xiyuan-fengyu** [comment]
要通过key去查询数据库，但是结果异步的情况吗

**Comment by gankbat** [comment]
对

**Comment by xiyuan-fengyu** [comment]
修复好了,试试预览版 2.1.10-preview.1559713782910  
例子 https://github.com/xiyuan-fengyu/ppspider/blob/master/src/test/component/AsyncFilterTest.ts

**Comment by gankbat** [comment]
好的
