### ISSUE TITLE
失败后不重试

### ISSUE THREAD

**Issue by gankbat** [xiyuan-fengyu/ppspider#4]
![image](https://user-images.githubusercontent.com/22650353/58956867-03e91680-87d2-11e9-91c7-a800336fa669.png)
![image](https://user-images.githubusercontent.com/22650353/58956881-0b102480-87d2-11e9-9095-c827f7c84fb5.png)

失败后 触发了 addJobToQueue 但是貌似没有重新入队列

**Comment by xiyuan-fengyu** [comment]
试试这个版本 2.1.10-preview.1559739580863  
之前改那个功能改出bug了

**Comment by gankbat** [comment]
![image](https://user-images.githubusercontent.com/22650353/59000926-45fc7180-883f-11e9-8ce4-078e1a3481b0.png)
![image](https://user-images.githubusercontent.com/22650353/59000936-514f9d00-883f-11e9-84e5-7a792b1c6e54.png)
这个队列的失败次数不对吧

**Comment by xiyuan-fengyu** [comment]
每个队列的fail数记录的是单次尝试失败的次数，顶上的fail数记录的是最大尝试次数用完后仍未成功的任务数，两个意思不一样，我在这两个上面加上title解释一下

**Comment by gankbat** [comment]
好的
