### ISSUE TITLE
PuppeteerUtil.useProxy不能携带proxy前的cookies继续访问?

### ISSUE THREAD

**Issue by wokao98** [xiyuan-fengyu/ppspider#5]
你好，我用了useProxy出现了这个问题。请问我应该如何处理呢，谢谢。

//Login Successful
await PuppeteerUtil.useProxy(page, proxy);
//refresh or click(link)
//重新登录。。。。

**Comment by xiyuan-fengyu** [comment]
await PuppeteerUtil.useProxy(page, proxy);  实际上是拦截了浏览器发起的请求，然后通过 request + http(s)-proxy-agent的方式继续发送原请求，所以cookie也是包含在请求里面的。你可以在PuppeteerUtil.useProxy 中 const proxyRes = await RequestUtil.simple(options);  一行添加一个断点，调试一下，看看请求options中是否包含cookie信息。

**Comment by wokao98** [comment]
我使用了await page.setRequestInterception(false); 
 来调试代理的情况，发现在拦截后这个page的ajax请求全部都hang住了，并且在cookies失效。

**Comment by xiyuan-fengyu** [comment]
await page.setRequestInterception(true); 这里必须是 true，否者请求只能监听，不能被拦截。

**Comment by wokao98** [comment]
const proxyRes = await RequestUtil.simple(options); 
我在这里看到req.headers()里面没有包含cookie对象。
在puppeteer的issues里面也有人提出了这个问题。https://github.com/GoogleChrome/puppeteer/issues/469
貌似还没有解决办法。。

**Comment by xiyuan-fengyu** [comment]
你可以把 useProxy 方法修改一下，通过 page.evaluate 注入一段js代码，获取cookie，然后把cookie添加到header里面

**Comment by wokao98** [comment]
我尝试过添加jar，一直失败。。
```
let cookies_var= "tradeLdc=NJYH; SN_SESSION_ID=xxxxx";
...
let jar = request.jar();
jar.setCookie(cookies_var, req.url());
const options = {
url: req.url(),
method: req.method(),
headers: req.headers(),
body: req.postData(),
proxy: proxy,
jar:jar
};
const proxyRes = await simple(options);
```

**Comment by xiyuan-fengyu** [comment]
没看懂你这段代码要干嘛；如果是要上传jar包，应该把jar包的Buffer设置到 options.body 字段

**Comment by wokao98** [comment]
> 没看懂你这段代码要干嘛；如果是要上传jar包，应该把jar包的Buffer设置到 options.body 字段

不好意思，我表达不好。我尝试用cookiejar的方式添加cookies到header里面。但是一直失败

**Comment by xiyuan-fengyu** [comment]
尝试一下这么改  
```typescript
const cookie = await page.evaluate(() => document.cookie);
const headers = Object.assign({}, req.headers());
headers.Cookie = cookie;
const options = {
    url: req.url(),
    method: req.method(),
    headers: headers,
    body: req.postData(),
    proxy: proxy
};
```

**Comment by wokao98** [comment]
> 尝试一下这么改
> 
> ```ts
> const cookie = await page.evaluate(() => document.cookie);
> const headers = Object.assign({}, req.headers());
> headers.Cookie = cookie;
> const options = {
>     url: req.url(),
>     method: req.method(),
>     headers: headers,
>     body: req.postData(),
>     proxy: proxy
> };
> ```

还是失败了。不清楚是不是数据格式不合法，headers.Cookie = cookie;   后会卡着整个page

**Comment by wokao98** [comment]
可能是DevTools协议不能给出全部的请求头
https://github.com/GoogleChrome/puppeteer/issues/3436

**Comment by xiyuan-fengyu** [comment]
我想到个办法，你可以在浏览里面正常访问抓取的页面，然后在network里面分析你关注的请求协议，然后用RequestUtil.simple自行发起请求，并设置代理，cookie可以通过 page.cookies 方法来获取

**Comment by wokao98** [comment]
其实我最早的想法跟这个一样https://github.com/GoogleChrome/puppeteer/issues/678
通过”上下游代理实施“  在本地搭建一个“下游” 接受一个特殊的userragent(包含真正代理的字符串)，再通过MITMPROXY这种中间人分别upstream出去
但是实施起来有点复杂，并且那个朋友也说了在HTTPS网站可能会有问题。。如果从puppeteer入手没法解决的话，可能我也只能这么做了。

**Comment by xiyuan-fengyu** [comment]
这个想法我之前已经实践过，主要是 page.setUserAgent 对于 https代理的connect方法无效，无论怎么设置user-agent，中间代理在接到connect请求时，header中的user-agent都是浏览器真实的值，所以中间代理无法通过user-agent来识别是哪一个page发起的请求，也没办法解析https加密后的内容，所以这个问题还是比较麻烦的

**Comment by xiyuan-fengyu** [comment]
新的预览版中，PuppeteerUtil.useProxy 会自动检测并添加cookies，试试看能否解决你的问题

**Comment by wokao98** [comment]
> 新的预览版中，PuppeteerUtil.useProxy 会自动检测并添加cookies，试试看能否解决你的问题

谢谢，我晚点去试试。刚刚发现我的目标网站用到了WEBRTC泄漏去校验真实IP,headless mode没办法过这一校验。只能用有头，所以偷了个懒写个PAC文件去通过了。

**Comment by wokao98** [comment]
> 新的预览版中，PuppeteerUtil.useProxy 会自动检测并添加cookies，试试看能否解决你的问题

你好，cookies问题解决了。但是当useProxy 和setImgLoad 同时使用的话，exPage的overrideMultiRequestListenersLogic工作好像不正常，没法continue

**Comment by xiyuan-fengyu** [comment]
我用这个例子 https://github.com/xiyuan-fengyu/ppspider/blob/master/src/test/component/ProxyTest.ts 测试了一下，没法重现你说的问题。方便的话，提供一下爬取网页地址和相关的代码。

**Comment by wokao98** [comment]
> 我用这个例子 https://github.com/xiyuan-fengyu/ppspider/blob/master/src/test/component/ProxyTest.ts 测试了一下，没法重现你说的问题。方便的话，提供一下爬取网页地址和相关的代码。

    const page = await get_page();
    await setImgLoad(page,false);
    await usePageProxy(page,"http://127.0.0.1:6336");   
    await page.goto("https://www.google.com");

是我的问题。工作正常的。。

**Comment by wokao98** [comment]
你好，我使用page proxy，在一些网站上会通过webrtc泄漏IP地址，headless: false可以使用Extensions解决，但是headless: true不支持Extensions。。请问下可以怎么处理呢。谢谢。。

**Comment by xiyuan-fengyu** [comment]
我没有处理过这方面的问题，搜了一些资料，感觉可以通过自己实现一个webRTC服务器充当中间人，并重写 window.RTCPeerConnection || window.mozRTCPeerConnection || window.webkitRTCPeerConnection 这些方法，让浏览器连接自己的webRTC服务器，然后在自己的webRTC服务器中与实际的webRTC服务器通讯，并将IP地址的信息修改掉

**Comment by wokao98** [comment]
重新实现一个webRTC服务器好像有点复杂啊。能不能从网络上禁掉webRTC的通讯端口呢？

**Comment by xiyuan-fengyu** [comment]
如果禁用webRTC，后续网页能正常工作，那可以参考 [这里](https://github.com/xiyuan-fengyu/ppspider_example/blob/master/src/examples/DisableWebRTC.ts)  覆盖 RTCPeerConnection 类定义，从而禁用webRTC

**Comment by wokao98** [comment]
谢谢，我去测试下。

**Comment by wokao98** [comment]
可以顺便请教下吗？有没有什么轮子是把puppeteer做成服务，把浏览器进程留在客户机器上本地运行的呢，谢谢。

**Comment by xiyuan-fengyu** [comment]
https://github.com/GoogleChrome/puppeteer/blob/v1.19.0/docs/api.md#puppeteerconnectoptions
