### ISSUE TITLE
Regexp url filter not work with toString

### ISSUE THREAD

**Issue by blu3gui7ar** [xiyuan-fengyu/ppspider#7]
https://github.com/xiyuan-fengyu/ppspider/blob/4d21e46046b26dcd3d98392dc4974d5c65817a88/src/puppeteer/PuppeteerUtil.ts#L160

Should use item.url directly

`return requestUrl.match(item.url) != null || checkUrl === requestUrl;`

**Comment by xiyuan-fengyu** [comment]
fixed  
https://github.com/xiyuan-fengyu/ppspider/commit/c90dabd4e96266867c00fe1cbade910f6a3fa204  
https://www.npmjs.com/package/ppspider/v/2.2.3-preview.1569121574515

**Comment by blu3gui7ar** [comment]
Seems you forgot to generate lib/spider/ui/web

**Comment by xiyuan-fengyu** [comment]
> Seems you forgot to generate lib/spider/ui/web

fixed in the new preview version
