### ISSUE TITLE
Enable socks proxy support

### ISSUE THREAD

**Issue by blu3gui7ar** [xiyuan-fengyu/ppspider#8]
https://github.com/xiyuan-fengyu/ppspider/blob/c90dabd4e96266867c00fe1cbade910f6a3fa204/src/common/util/RequestUtil.ts#L55

It will be awesome if [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent) is supported here.

```
if (options.proxy.startsWith("socks")) {
  options.agent = new SocksProxyAgent(options.proxy);
}
```

**Comment by xiyuan-fengyu** [comment]
https://github.com/xiyuan-fengyu/ppspider/commit/316eb608760f71a3a0a7c09a75c57a92627a89aa  
https://www.npmjs.com/package/ppspider/v/2.2.3-preview.1569208986875

**Comment by blu3gui7ar** [comment]
Impressively quick reaction!
