### ISSUE TITLE
PuppeteerUtil.useProxy, How to set args "--proxy-bypass-list = ***"

### ISSUE THREAD

**Issue by adams-king** [xiyuan-fengyu/ppspider#9]
PuppeteerUtil.useProxy, How to set args "--proxy-bypass-list = ***"
please help me, thanks!

**Comment by xiyuan-fengyu** [comment]
try this  
```
import {Job, Launcher, OnStart, Page, PromiseUtil, PuppeteerUtil, PuppeteerWorkerFactory} from "../..";

class TestTask {

    @OnStart({
        urls: [
            "https://www.baidu.com"
        ]
    })
    async onStart(page: Page, job: Job) {
        await page.on("request", async req => {
            // continue those requests matched in bypass-list to avoid the proxy handler
            if (req.url().match("baidu.com|test.com")) {
                await req.continue();
            }
        });
        await PuppeteerUtil.useProxy(page, "http://127.0.0.1:2007");
        await page.goto(job.url);
        console.log(await page.evaluate(() => document.title));
        await PromiseUtil.sleep(10000000);
    }

}

@Launcher({
    workplace: "workplace",
    tasks: [
        TestTask
    ],
    workerFactorys: [
        new PuppeteerWorkerFactory({
            headless: false,
            devtools: true
        })
    ],
    webUiPort: 9001
})
class App {}
```

**Comment by adams-king** [comment]
> try this
> 
> ```
> import {Job, Launcher, OnStart, Page, PromiseUtil, PuppeteerUtil, PuppeteerWorkerFactory} from "../..";
> 
> class TestTask {
> 
>     @OnStart({
>         urls: [
>             "https://www.baidu.com"
>         ]
>     })
>     async onStart(page: Page, job: Job) {
>         await page.on("request", async req => {
>             // continue those requests matched in bypass-list to avoid the proxy handler
>             if (req.url().match("baidu.com|test.com")) {
>                 await req.continue();
>             }
>         });
>         await PuppeteerUtil.useProxy(page, "http://127.0.0.1:2007");
>         await page.goto(job.url);
>         console.log(await page.evaluate(() => document.title));
>         await PromiseUtil.sleep(10000000);
>     }
> 
> }
> 
> @Launcher({
>     workplace: "workplace",
>     tasks: [
>         TestTask
>     ],
>     workerFactorys: [
>         new PuppeteerWorkerFactory({
>             headless: false,
>             devtools: true
>         })
>     ],
>     webUiPort: 9001
> })
> class App {}
> ```

It's Done, many thanks!
